Repository fission/fission, pull requests merged in 2021-09, with the labels that each got.

#2191 ci(Mergify): configuration update
  .mergify.yml
Labels: ready-to-merge

#2194 fix: Use standard env variables for opentelemtry
  charts/fission-all/templates/_helpers.tpl
  charts/fission-all/templates/deployment.yaml
  charts/fission-all/templates/router.yaml
  charts/fission-all/values.yaml
  charts/fission-core/templates/_helpers.tpl
  charts/fission-core/templates/deployment.yaml
  charts/fission-core/templates/router.yaml
  charts/fission-core/values.yaml
  cmd/fetcher/app/server.go
  cmd/fission-bundle/main.go
  go.mod
  pkg/fetcher/config/config.go
  pkg/utils/otel/provider.go
  pkg/utils/tracing/tracing.go
  skaffold.yaml
Labels: ready-to-merge

#2195 chore(dep): update go dependency stow v0.2.7
  go.mod
  go.sum
Labels: ready-to-merge

#2186 fix: Updated nats connector version to v0.9
  charts/fission-all/values.yaml
  charts/fission-core/values.yaml
Labels: ready-to-merge

#2201 enhancement: Add different samplers and propagators support with OpenTelemetry
  charts/fission-all/templates/_helpers.tpl
  charts/fission-all/values.yaml
  charts/fission-core/templates/_helpers.tpl
  charts/fission-core/values.yaml
  go.mod
  go.sum
  pkg/fission-cli/cmd/function/test.go
  pkg/utils/otel/provider.go
  pkg/utils/otel/provider_test.go
Labels: ready-to-merge

#2203 chore(changelog): Cleanup changelog and exclude non-standard releases
  CHANGELOG.md
  hack/changelog.sh
  hack/ignore_tags
Labels: no-changelog

#2204 Prerelease v1.15.0-rc1
  charts/fission-all/Chart.yaml
  charts/fission-all/values.yaml
  charts/fission-core/Chart.yaml
  charts/fission-core/values.yaml
Labels: no-changelog

#2205 Update changelog
  CHANGELOG.md
Labels: no-changelog

#2210 Update docs link to fission.io/docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .goreleaser.yml
  CONTRIBUTING.md
  Documentation/README.md
  README.md
  cmd/fission-cli/app/app.go
  hack/Releasing.md
  hack/notes.md
Labels: ready-to-merge, no-changelog
