Repository fission/fission, pull requests merged in 2021-06, with the labels that each got.

#2048 Add role required by fetcher pod to fetch events & pods in helm chart
  .github/workflows/push_pr.yaml
  charts/fission-all/Chart.lock
  charts/fission-all/templates/deployment.yaml
  charts/fission-core/Chart.lock
  charts/fission-core/templates/deployment.yaml
  fetcher-pod-sa.yaml
Labels: ready-to-merge

#1929 Multiarch release
  Makefile
  hack/buildx.sh
  hack/release.sh
Labels: ready-to-merge

#2044 Change container name for runtime container to environment name in newdeploy
  pkg/apis/core/v1/validation.go
  pkg/executor/executortype/newdeploy/newdeploy.go
  test/tests/test_specs/test_spec_merge/specs/env-nodend.yaml
Labels: ready-to-merge

#2052 Wait for small time to avoid timeout in specs tests
  test/tests/test_specs/test_spec_merge/test_spec_merge.sh
  test/tests/test_specs/test_spec_multifile.sh
Labels: ready-to-merge

#2050 Added fission upgrade workflow
  .github/workflows/upgrade_test.yaml
  test/upgrade_test/fission_objects.sh
Labels: ready-to-merge

#1830 Response body in error topic
  pkg/mqtrigger/messageQueue/kafka/kafka.go
Labels: ready-to-merge

#2059 Move RBAC v1beta1 to v1
  pkg/executor/reaper/reaper.go
  pkg/utils/rbacutils.go
Labels: ready-to-merge

#2053 Add websocket test
  test/kind_CI.sh
  test/test_utils.sh
  test/tests/websocket/broadcast.js
  test/tests/websocket/go.mod
  test/tests/websocket/go.sum
  test/tests/websocket/main.go
  test/tests/websocket/specs/env-nodejs.yaml
  test/tests/websocket/specs/fission-deployment-config.yaml
  test/tests/websocket/specs/function-bs.yaml
  test/tests/websocket/test_ws.sh
Labels: ready-to-merge

#2047 Enable prefix based routing
  crds/v1/fission.io_httptriggers.yaml
  pkg/apis/core/v1/types.go
  pkg/apis/core/v1/zz_generated.deepcopy.go
  pkg/canaryconfigmgr/canaryConfigMgr.go
  pkg/controller/httpTriggerApi.go
  pkg/fission-cli/cmd/function/command.go
  pkg/fission-cli/cmd/function/create.go
  pkg/fission-cli/cmd/function/test.go
  pkg/fission-cli/cmd/httptrigger/command.go
  pkg/fission-cli/cmd/httptrigger/create.go
  pkg/fission-cli/cmd/httptrigger/update.go
  pkg/fission-cli/cmd/spec/list.go
  pkg/fission-cli/cmd/spec/spec.go
  pkg/fission-cli/flag/flag.go
  pkg/fission-cli/flag/key/key.go
  pkg/fission-cli/util/util.go
  pkg/router/functionHandler.go
  pkg/router/httpTriggers.go
  pkg/router/util/util.go
  test/utils.sh
Labels: waiting-for-review

#2061 Add a SharedIndexInformer for services and deployments to NewDeploy executor
  pkg/executor/executor.go
  pkg/executor/executortype/newdeploy/newdeploymgr.go
  pkg/executor/executortype/poolmgr/gp.go
  pkg/executor/executortype/poolmgr/gpm.go
  pkg/poolcache/poolcache.go
  pkg/utils/informer.go
Labels: ready-to-merge, waiting-for-review

#2065 Added GCP PubSub Image, enabled Keda by default and updated versions of all Keda connector images
  charts/fission-all/templates/deployment.yaml
  charts/fission-all/values.yaml
  charts/fission-core/templates/deployment.yaml
  charts/fission-core/values.yaml
Labels: ready-to-merge
