Repository fission/fission, pull requests merged in 2022-01, with the labels that each got.

#2279 feature: Apply commit label on resources created/updated when '--commitlabel' is passed
  pkg/fission-cli/cmd/function/create.go
  pkg/fission-cli/cmd/httptrigger/create.go
  pkg/fission-cli/cmd/kubewatch/create.go
  pkg/fission-cli/cmd/mqtrigger/create.go
  pkg/fission-cli/cmd/package/create.go
  pkg/fission-cli/cmd/package/package.go
  pkg/fission-cli/cmd/spec/apply.go
  pkg/fission-cli/cmd/spec/command.go
  pkg/fission-cli/cmd/spec/destroy.go
  pkg/fission-cli/cmd/spec/list.go
  pkg/fission-cli/cmd/spec/spec.go
  pkg/fission-cli/cmd/spec/validate.go
  pkg/fission-cli/cmd/timetrigger/create.go
  pkg/fission-cli/flag/flag.go
  pkg/fission-cli/flag/key/key.go
  pkg/fission-cli/util/constants.go
  pkg/utils/gitrepo/gitrepo.go
Labels: documentation

#2298 Kafka connector namespace issue
  pkg/mqtrigger/scalermanager.go
Labels: documentation

#2302 Rbac resources per release
  charts/fission-all/templates/buildermgr/deployment.yaml
  charts/fission-all/templates/common/clusterrole.yaml
  charts/fission-all/templates/common/clusterrolebinding.yaml
  charts/fission-all/templates/executor/deployment.yaml
  charts/fission-all/templates/misc-functions/clusterrole.yaml
  charts/fission-all/templates/misc-functions/role.yaml
  charts/fission-all/templates/misc-functions/rolebinding.yaml
  charts/fission-all/values.yaml
  pkg/apis/core/v1/const.go
  pkg/buildermgr/pkgwatcher.go
  pkg/executor/executortype/newdeploy/newdeploy.go
  pkg/executor/executortype/poolmgr/funchandlers.go
  pkg/executor/executortype/poolmgr/packagehandlers.go
  pkg/utils/rbacutils.go
Labels: ready-to-merge

#2337 make graceperiod configurable for container functions
  pkg/executor/executortype/container/deployment.go
  pkg/fission-cli/cmd/function/command.go
  pkg/fission-cli/cmd/function/run_container.go
  pkg/fission-cli/flag/flag.go
  pkg/fission-cli/flag/key/key.go
Labels: ready-to-merge

#2339 Change URL structure for CLI docs with reference
  Makefile
  tools/cmd-docs/main.go
Labels: no-changelog
