Repository fission/fission, pull requests merged in 2022-09, with the labels that each got.

#2519 Add grafana dashboards and configmap creation for auto provisioning
  charts/fission-all/dashboards/.lint
  charts/fission-all/dashboards/fission-admin-dashboard.json
  charts/fission-all/dashboards/fission-user-dashboard.json
  charts/fission-all/templates/dashboards/dashboards.yaml
  charts/fission-all/values.yaml
  hack/lint-dashboards.sh
Labels: area-observability

#2540 allow two http trigger with no url and different prefix
  pkg/controller/api_test.go
  pkg/controller/httpTriggerApi.go
Labels: ready-to-merge

#2552 Inject open telemetry(OTEL) transport in executor
  pkg/executor/client/client.go
Labels: area-executor
